name: "khulnasoft code test"
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: khulnasoft/actions/setup@master
      - name: Khulnasoft Test
        run: khulnasoft code test --org=${{ secrets.KHULNASOFT_ORG }} --sarif > khulnasoft-sarif2.json
        continue-on-error: true
        env:
           KHULNASOFT_TOKEN: ${{ secrets.KHULNASOFT_TOKEN }}
      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: khulnasoft-sarif2.json
